#%RAML 0.8
title: global-api
baseUri: https://www.hmislynk.com/hmis-clientapi/rest
version: 1.0.0
/search/{searchentity}:
  get:
    description: |
          The Search API is optimized to find the specific entity you're looking for (e.g., a client, enrollments, etc.).It's designed to  find the one result you're looking for (or maybe the few results you're looking for). Currently hmislynk supporting search on 'clients' entity only. Just like searching on Google, you sometimes want to see a few pages of search results so that you can find the item that best meets your needs.  HMISLynk Search API provides up to 50 results for each searh. However, the search results can be limited by the client.
            Note: Current suppoerting URI  is /search/clients and /search/projects
    queryParameters:
      q:
        description: |
             The search keywords for clients, as well as any qualifiers.Currently supported search fields are first name,middle name,last name,dob,source system id and ssn. For search on "date of birth" field the format MM-dd-YYYY should be used for the search keyword.
             
             The seach keywords for projects, as well as any qualifiers. Currenly supported search fields are projectName, projectCommonName, projectId.
      sort:
        description: The sort field. Default- results are sorted by "created date".
        type: string
        example: created date
      order:
        description: The sort order if sort parameter is provided. One of asc or desc. Default- desc.
        type: string
        example: desc
        default: desc
      startIndex:
        description: The start Index from where the search results should be returned. Default - 0 
        type: integer
        example: 0
        default: 0
      maxItems:
        description: the number or Items that should be included in the results . Default - 50
        type: integer
        example: 50
        default: 50
      exclude:
         description: | 
            Excludes flieds from the search.Currently it suppoted value is "ssi" (to exclude source system id) only.
    responses:
      200:
        body:
          application/json:
            example: |   
                  sample search response for client search
                  {
                  "searchResults": {
                    "pagination": {
                      "total":"2"
                      "from": "0",
                      "maximum": "50",
                      "returned":"2"
                    },
                    "items": [
                      {
                        "clientId": "65e3df62-dd22-4d07-83ef-6858a6322839",
                        "firstName": "Eric",
                        "middleName": "Eric",
                        "lastName": "Eric",
                        "nameSuffix": "NS ",
                        "nameDataQuality": "1",
                        "ssn": "ssn ",
                        "ssnDataQuality": "1",
                        "dob": "1459498034983",
                        "dobDataQuality": "1",
                        "race": "1",
                        "ethnicity": "1",
                        "gender": "1",
                        "otherGender": "Test",
                        "veteranStatus": "8",
                        "link":"/hmis-clientapi/rest/v2015/clients/65e3df62-dd22-4d07-83ef-6858a6322839"
                      },
                      {
                        "clientId": "cf98b9b2-9a77-4133-99a3-b60f05a12ad1",
                        "firstName": "Eric",
                        "middleName": "Eric",
                        "lastName": "Eric",
                        "nameSuffix": "NS ",
                        "nameDataQuality": "1",
                        "ssn": "ssn ",
                        "ssnDataQuality": "1",
                        "dob": "1459498034983",
                        "dobDataQuality": "1",
                        "race": "1",
                        "ethnicity": "1",
                        "gender": "1",
                        "otherGender": "Test",
                        "veteranStatus": "8",
                        "link":"/hmis-clientapi/rest/v2014/clients/cf98b9b2-9a77-4133-99a3-b60f05a12ad1"
                      }
                    ]
                  }
                  }
                   sample search response for projects search
                  {
                   "searchResults":{
                      "pagination":{
                         "from":0,
                         "returned":1,
                         "total":1,
                         "maximum":50,
                         "sort":{
                            "field":"id",
                            "order":"asc"
                         }
                      },
                      "items":[
                         {
                            "projectId":"066c95d3-c97c-40b9-b8c1-bf12cafdfca4",
                            "projectName":"ProjectName_1459515376900",
                            "projectCommonName":"ProjectCommonName_1459515376900",
                            "continuumProject":0,
                            "projectType":2,
                            "targetPopulation":3,
                            "trackingMethod":0,
                            "schemaYear":2015,
                            "link":"/hmis-clientapi/rest/v2015/projects/066c95d3-c97c-40b9-b8c1-bf12cafdfca4",
                            "projectGroup":"HO0002"
                         }
                      ]
                     }
                      }
           