#%RAML 1.0
title: Global Human Services
version: 1.3.3
mediaType: application/json
protocols:
  - HTTPS
baseUri: 'https://www.hmislynk.com/hmis-globalapi/rest'
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
resourceTypes:
  collection:
    description: 'Operations performed on the set of all HMIS <<resourcePathName>> within the system, and for adding a new <<resourcePathName|!singularize>> to the set of <<resourcePathName>> '
  member:
    get:
      description: |
        The Search API is optimized to find the specific entity you're looking for (e.g., a client, enrollments, etc.).  It's designed to  find the one result you're looking for (or maybe the few results you're looking for). Currently hmislynk supporting search on 'clients' entity only. Just like searching on Google, you sometimes want to see a few pages of search results so that you can find the item that best meets your needs.  HMISLynk Search API provides up to 50 results for each search.  However, the search results can be limited by the client.  Note: Current supporting URI is /search/clients
      queryParameters:
        q:
         description: |
           * The search keywords for clients, as well as any qualifiers.Currently supported search fields are first name,middle name,last name,dob,source system id and ssn. For search on "date of birth" field the format MM-dd-YYYY should be used for the search keyword.
         required: false
        consentGroupId:
          description: |
             Consent Group ID to filter the clients.
          required: false
        sort:
         description: The sort field. Default- results are sorted by "created date".
         example: created date
         type: string
        order:
         description: The sort order if sort parameter is provided. One of asc or desc. Default- desc.
         example: desc
         default: desc
         type: string
        startIndex:
         description: The start Index from where the search results should be returned. Default - 0
         example: 0
         default: 0
         type: integer
        maxItems:
         description: the number or Items that should be included in the results . Default - 50
         example: 50
         default: 50
         type: integer
        exclude:
         description: |
           Excludes flieds from the search.Currently it suppoted value is "ssi" (to exclude source system id) only.
      responses:
        '200':
          description: OK – Everything is working.
          body:
            application/json:
              required: false
              example: |
                example search response for client search:

                  {
                    "searchResults": {
                      "pagination": {
                        "total":"2"
                        "from": "0",
                        "maximum": "50",
                        "returned":"2"
                      },
                      "items": [
                        {
                          "clientId": "65e3df62-dd22-4d07-83ef-6858a6322839",
                          "firstName": "Eric",
                          "middleName": "Eric",
                          "lastName": "Eric",
                          "nameSuffix": "NS ",
                          "nameDataQuality": "1",
                          "ssn": "ssn ",
                          "ssnDataQuality": "1",
                          "dob": "1459498034983",
                          "dobDataQuality": "1",
                          "race": "1",
                          "ethnicity": "1",
                          "gender": "1",
                          "otherGender": "Test",
                          "veteranStatus": "8",
                          "link":"/hmis-clientapi/rest/v2015/clients/65e3df62-dd22-4d07-83ef-6858a6322839"
                        },
                        {
                          "clientId": "cf98b9b2-9a77-4133-99a3-b60f05a12ad1",
                          "firstName": "Eric",
                          "middleName": "Eric",
                          "lastName": "Eric",
                          "nameSuffix": "NS ",
                          "nameDataQuality": "1",
                          "ssn": "ssn ",
                          "ssnDataQuality": "1",
                          "dob": "1459498034983",
                          "dobDataQuality": "1",
                          "race": "1",
                          "ethnicity": "1",
                          "gender": "1",
                          "otherGender": "Test",
                          "veteranStatus": "8",
                          "link":"/hmis-clientapi/rest/v2014/clients/cf98b9b2-9a77-4133-99a3-b60f05a12ad1"
                        }
                      ]
                    }
                  }

                and example search response for projects search:

                  {
                   "searchResults":{
                      "pagination":{
                         "from":0,
                         "returned":1,
                         "total":1,
                         "maximum":50,
                         "sort":{
                            "field":"id",
                            "order":"asc"
                         }
                      },
                      "items":[
                         {
                            "projectId":"066c95d3-c97c-40b9-b8c1-bf12cafdfca4",
                            "projectName":"ProjectName_1459515376900",
                            "projectCommonName":"ProjectCommonName_1459515376900",
                            "continuumProject":0,
                            "projectType":2,
                            "targetPopulation":3,
                            "trackingMethod":0,
                            "schemaYear":2015,
                            "link":"/hmis-clientapi/rest/v2015/projects/066c95d3-c97c-40b9-b8c1-bf12cafdfca4",
                            "projectGroup":"HO0002"
                         }
                      ]
                    }
                  }
        '400':
          description: Bad Request – The request was invalid or cannot be served.
        '401':
          description: Unauthorized – The request requires an user authentication.
        '403':
          description: 'Forbidden – The server understood the request, but is refusing it or the access is not allowed.'
        '404':
          description: Not found – There is no resource behind the URI.
        '500':
          description: Internal Server Error
/search:
  '/{searchentity}':
    type: member
/global-projects:
  post:
    description: Create a global project
    body:
        application/json:
          example:
                  {
                     "globalProject":{
                        "projectName":"Project Name",
                        "projectCommonName":"Project common name",
                        "description":" description",
                        "sourceSystemId":"source123",
                        "projects":{
                           "projects":[
                              {
                                 "projectId":"f9748a7b-80ac-4ffd-86f7-c8e71416502f",
                                 "source":"2015"
                              },
                              {
                                 "projectId":"9a147cc3-7b78-4a82-abe4-f42f9ee59b61",
                                 "source":"2014"
                              }
                           ]
                        }
                     }
                  }
    responses:
      200:
        body:
          application/json:
            example:
                    {
                       "globalProject":{
                          "id":"661189b2-183f-4d03-aba0-7d3050b62a5f",
                          "projectName":"Project Name",
                          "projectCommonName":"Project common name",
                          "description":" description",
                          "sourceSystemId":"source123",
                          "projects":{
                             "projects":[
                                {
                                   "projectId":"f9748a7b-80ac-4ffd-86f7-c8e71416502f",
                                   "source":"2015"
                                },
                                {
                                   "projectId":"9a147cc3-7b78-4a82-abe4-f42f9ee59b61",
                                   "source":"2014"
                                }
                             ]
                          }
                       }
                    }
  get:
    description: Get all global projects
    responses:
      200:
        body:
          application/json:
            example:
                      {
                         "globalProjects":{
                            "pagination":{
                               "from":0,
                               "returned":2,
                               "total":2,
                               "maximum":30,
                               "sort":{

                               }
                            },
                            "globalProjects":[
                               {
                                  "id":"38d97c40-ef8f-465a-9ede-d8933385c0ed",
                                  "projectName":"name",
                                  "projectCommonName":"common name",
                                  "description":"descrption",
                                  "sourceSystemId":"source123",
                                  "projects":{
                                     "projects":[
                                        {
                                           "projectId":"f9748a7b-80ac-4ffd-86f7-c8e71416502f",
                                           "source":"2015",
                                           "link":"/hmis-clientapi/v2015/rest/projects/f9748a7b-80ac-4ffd-86f7-c8e71416502f"
                                        },
                                        {
                                           "projectId":"9a147cc3-7b78-4a82-abe4-f42f9ee59b61",
                                           "source":"2014",
                                           "link":"/hmis-clientapi/v2014/rest/projects/9a147cc3-7b78-4a82-abe4-f42f9ee59b61"
                                        },
                                        {
                                           "projectId":"9d278142-978d-461e-8aea-07d629e462e8",
                                           "source":"2014",
                                           "link":"/hmis-clientapi/v2014/rest/projects/9d278142-978d-461e-8aea-07d629e462e8"
                                        }
                                     ]
                                  }
                               },
                               {
                                  "id":"d0242f55-c019-41c2-8f0c-6dadbb38c875",
                                  "projectName":"Project Name",
                                  "projectCommonName":"Project common name",
                                  "description":" description",
                                  "sourceSystemId":"source123",
                                  "projects":{
                                     "projects":[
                                        {
                                           "projectId":"f9748a7b-80ac-4ffd-86f7-c8e71416502f",
                                           "source":"2015",
                                           "link":"/hmis-clientapi/v2015/rest/projects/f9748a7b-80ac-4ffd-86f7-c8e71416502f"
                                        },
                                        {
                                           "projectId":"9a147cc3-7b78-4a82-abe4-f42f9ee59b61",
                                           "source":"2014",
                                           "link":"/hmis-clientapi/v2014/rest/projects/9a147cc3-7b78-4a82-abe4-f42f9ee59b61"
                                        }
                                     ]
                                  }
                               }
                            ]
                         }
                      }
/global-projects/{global-projectId}:
  put:
    description: Update selected global project
    body:
        application/json:
          example:
                      {
                       "globalProject":{
                         "projectName":"Sample Project Name",
                         "projectCommonName":"Sample Project Common Name",
                         "description":"Sample Project description"
                       }
                      }
    responses:
      200:
        body:
          application/json:
            example:
                  {
                   "globalProject": {
                     "projectId":"3d65a9bc-af57-4e3e-bc4d-29d661767ac9",
                     "projectName":"Sample Project Name",
                     "projectCommonName":"Sample Project Common Name",
                     "description":"Sample Project description"
                   }
                  }

  get:
    description: Get selected global project
    responses:
      200:
        body:
          application/json:
            example:
                      {
                         "globalProject":{
                            "id":"d0242f55-c019-41c2-8f0c-6dadbb38c875",
                            "projectName":"Project Name",
                            "projectCommonName":"Project common name",
                            "description":" description",
                            "projects":{
                               "projects":[
                                  {
                                     "projectId":"f9748a7b-80ac-4ffd-86f7-c8e71416502f",
                                     "source":"2015",
                                     "link":"/hmis-clientapi/v2015/rest/projects/f9748a7b-80ac-4ffd-86f7-c8e71416502f"
                                  },
                                  {
                                     "projectId":"9a147cc3-7b78-4a82-abe4-f42f9ee59b61",
                                     "source":"2014",
                                     "link":"/hmis-clientapi/v2014/rest/projects/9a147cc3-7b78-4a82-abe4-f42f9ee59b61"
                                  }
                               ]
                            }
                         }
                      }
/global-projects/{global-projectId}/projects:
  put:
    description: Add projects to selected global project
    body:
      application/json:
        example:
          {
             "projects":{
                "projects":[
                   {
                      "projectId":"9d278142-978d-461e-8aea-07d629e462e8",
                      "source":"2014"
                   },
                   {
                      "projectId":"a56fa6d8-b6c9-4838-b376-09af1306c063",
                      "source":"2016"
                   }
                ]
             }
          }
    responses:
      200:
        body:
          application/json:
/global-projects/{global-projectId}/projects/{projectId}:
  delete:
    description: Remove project from selected global project
    responses:
      200:
        body:
          application/json:
/global-projects/${globalProjectId}/users:
  put:
    description: Add users to a global project
    body:
      application/json:
        example: |
                  {
                  "users":{
                     "users":[
                        {
                           "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09367c"
                        },
                        {
                           "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09365c"
                        },
                        {
                           "userId":"183548a8-4f0e-4b3d-a114-c1e3043cf49d"
                        }
                     ]
                  }
                  }
  get:
    description: Retrive a global project users
    responses:
      200:
        body:
          application/json:
            example:
              {
                 "users":{
                    "users":[
                       {
                          "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09367c",
                          "username":"developeradmin@hmis.com",
                          "emailAddress":"hmisprojects@gmail.com",
                          "firstName":"Developer Admin",
                          "middleName":"Developer Admin",
                          "lastName":"Developer Admin",
                          "gender":0,
                          "status":"ACTIVE",
                          "link":"/hmis-user-service/rest/accounts/8b6c6ef2-87c7-47f0-8874-4cca6f09367c"
                       },
                       {
                          "userId":"183548a8-4f0e-4b3d-a114-c1e3043cf49d",
                          "username":"tes11tq@te42223s.com",
                          "emailAddress":"test@test.com",
                          "firstName":"First NameTest",
                          "middleName":"Middle name",
                          "lastName":"Last Name",
                          "gender":0,
                          "status":"ACTIVE",
                          "link":"/hmis-user-service/rest/accounts/183548a8-4f0e-4b3d-a114-c1e3043cf49d"
                       }
                    ]
                 }
              }
/global-projects/${globalProjectId}/users/{userId}:
  delete:
    description: Remove users from a global project
/clients/{clientDedupId}/global-enrollments:
  post:
    description: Create a global enrollment for a client
    body:
      application/json:
        example:
                {
                   "globalEnrollment":{
                      "enrollments":{
                         "enrollments":[
                            {
                               "enrollmentId":"637fbfbb-e75c-49f1-900f-1aa0015aefab",
                               "source":"2016",
                               "clientId":"6bf95840-8567-469b-9efe-8c6351294e55"
                            },
                            {
                               "enrollmentId":"d12a5b43-9411-4fe3-8cd3-0778459d0085",
                               "source":"2015",
                               "clientId":"d4a9b184-21ea-4136-b9b8-0d59e8ee7b71"
                            }
                         ]
                      }
                   }
                }
    responses:
      200:
        body:
          application/json:
            example:
              {
                 "globalEnrollment":{
                    "id":"bcd68553-08a0-4463-8713-3619f1022fc1",
                    "dedupClientId":"b3f60ea0-79a9-11e6-ab44-02f305dabccf",
                    "enrollments":{
                       "enrollments":[
                          {
                             "enrollmentId":"637fbfbb-e75c-49f1-900f-1aa0015aefab",
                             "clientId":"6bf95840-8567-469b-9efe-8c6351294e55",
                             "source":"2016",
                             "link":"hmis-clientapi/v2016/rest/clients/6bf95840-8567-469b-9efe-8c6351294e55/enrollments/637fbfbb-e75c-49f1-900f-1aa0015aefab"
                          },
                          {
                             "enrollmentId":"d12a5b43-9411-4fe3-8cd3-0778459d0085",
                             "clientId":"d4a9b184-21ea-4136-b9b8-0d59e8ee7b71",
                             "source":"2015",
                             "link":"hmis-clientapi/v2015/rest/clients/d4a9b184-21ea-4136-b9b8-0d59e8ee7b71/enrollments/d12a5b43-9411-4fe3-8cd3-0778459d0085"
                          }
                       ]
                    }
                 }
              }
  get:
    description: Get all global enrollment
    responses:
      200:
        body:
          application/json:
            example:
              {
                 "globalEnrollments":{
                    "pagination":{
                       "from":0,
                       "returned":1,
                       "total":1,
                       "maximum":30,
                       "sort":{

                       }
                    },
                    "globalEnrollments":[
                       {
                          "id":"a2919645-c366-49b9-a101-3b803fa15d3d",
                          "dedupClientId":"b3f60ea0-79a9-11e6-ab44-02f305dabccf",
                          "enrollments":{
                             "enrollments":[
                                {
                                   "id":"0ffdf949-b799-43d3-82ca-506478274a74",
                                   "enrollmentId":"637fbfbb-e75c-49f1-900f-1aa0015aefab",
                                   "clientId":"6bf95840-8567-469b-9efe-8c6351294e55",
                                   "source":"2016",
                                   "link":"hmis-clientapi/v2016/rest/clients/6bf95840-8567-469b-9efe-8c6351294e55/enrollments/637fbfbb-e75c-49f1-900f-1aa0015aefab"
                                },
                                {
                                   "id":"183b0b94-9d14-44ad-ad98-9408b328230d",
                                   "enrollmentId":"d12a5b43-9411-4fe3-8cd3-0778459d0085",
                                   "clientId":"d4a9b184-21ea-4136-b9b8-0d59e8ee7b71",
                                   "source":"2015",
                                   "link":"hmis-clientapi/v2015/rest/clients/d4a9b184-21ea-4136-b9b8-0d59e8ee7b71/enrollments/d12a5b43-9411-4fe3-8cd3-0778459d0085"
                                }
                             ]
                          }
                       }
                    ]
                 }
              }
/clients/{clientDedupId}/global-enrollments/{global-enrollmentId}:
  get:
    description: Get selected global enrollment
    responses:
      200:
        body:
          application/json:
            example:
              {
                 "globalEnrollment":{
                    "id":"a2919645-c366-49b9-a101-3b803fa15d3d",
                    "dedupClientId":"b3f60ea0-79a9-11e6-ab44-02f305dabccf",
                    "enrollments":{
                       "enrollments":[
                          {
                             "id":"0ffdf949-b799-43d3-82ca-506478274a74",
                             "enrollmentId":"637fbfbb-e75c-49f1-900f-1aa0015aefab",
                             "clientId":"6bf95840-8567-469b-9efe-8c6351294e55",
                             "source":"2016",
                             "link":"hmis-clientapi/v2016/rest/clients/6bf95840-8567-469b-9efe-8c6351294e55/enrollments/637fbfbb-e75c-49f1-900f-1aa0015aefab"

                          },
                          {
                             "id":"183b0b94-9d14-44ad-ad98-9408b328230d",
                             "enrollmentId":"d12a5b43-9411-4fe3-8cd3-0778459d0085",
                             "clientId":"d4a9b184-21ea-4136-b9b8-0d59e8ee7b71",
                             "source":"2015",
                             "link":"hmis-clientapi/v2015/rest/clients/d4a9b184-21ea-4136-b9b8-0d59e8ee7b71/enrollments/d12a5b43-9411-4fe3-8cd3-0778459d0085"
                          }
                       ]
                    }
                 }
              }
  delete:
    description: Delete selected global enrollment
/clients/{clientDedupId}/global-enrollments/{global-enrollmentId}/enrollments:
  put:
    description: Add enrollment to selected global enrollment
    body:
      application/json:
        example:
          {
            "enrollments": {
              "enrollments": [
                {
                  "enrollmentId": "637fbfbb-e75c-49f1-900f-1aa0015aefab",
                  "source": "2016",
                  "clientId":"6bf95840-8567-469b-9efe-8c6351294e55"

                },
                {
                  "enrollmentId": "d12a5b43-9411-4fe3-8cd3-0778459d0085",
                  "source": "2015",
                  "clientId":"d4a9b184-21ea-4136-b9b8-0d59e8ee7b71"
                }
              ]
            }
          }
    responses:
      200:
        body:
          application/json:
/clients/{clientDedupId}/global-enrollments/{global-enrollmentId}/enrollments/{enrollmentId}:
  delete:
    description: Remove enrollment from selected global enrollment
    responses:
      200:
        body:
          application/json:
/notifications:
  post:
    description: API to create a notification request. Any one of the recipients is mandatory (TO, CC or BCC). Multiple email addresses should be comma delimeted. "Body" and "Subject" are mandatory fields. Notification can be sent with "HIGH" priority by setting the "priority" value to 1. None of the elements with in "additionalInfo" section are mandatory.
    body:
      application/json:
        example:
                {
                   "notification":{
                      "method":"EMAIL",
                      "data":{
                         "recipients":{
                            "toRecipients":[
                               "surya.yadavalli@gmail.com",  "surya.yadavalli@hmislynk.com"
                            ],
                            "bccRecipients":[
                               "jceleldon@ctagroup.com"
                            ],
                            "ccRecipients":[
                               "admin@ctagroup.com"
                            ]
                         },
                         "body":"Test message",
                         "subject":"Test subject",
                         "priority":1
                      },

                      "additionalInfo":{
                         "messageType":"Cancellation Notice",
                         "recipientType":"clientID",
                         "recipientId":"18a93ad8-cced-49c5-9185-9cb3da9de89b"
                      }
                   }
                }
    responses:
      200:
        body:
          application/json:

      400:
        body:
          application/json:
            example:
              {
                 "errors":{
                    "error":[
                       {
                          "message":"Email body is required"
                       }
                    ]
                 }
              }

  get:
    description: !
            " GET the notification details along with their current status and timestamps. These details can be filtered using the following query parameters. Few examples below
              \n\n* hmis-globalapi/rest/notifications?fromdate=1516546276760 - Returns all the notifications sent from Sun Jan 21 2018 14:51:16
              \n\n* hmis-globalapi/rest/notifications?fromdate=1516521600000&todate=1516693923129 - Returns all notifications sent between Sun Jan 21 2018 08:00:00 and Tue Jan 23 2018 07:52:03
              \n\n* hmis-globalapi/rest/notifications?status=CREATED,DELIVERED - Returns all notifications that are with status CREATED and DELIVERED
              \n\n* hmis-globalapi/rest/notifications?recipienttype=clientid&recipientid=cf98b9b2-9a77-4133-99a3-b60f05a12ad1 - Returns all notifications associated with the client Id cf98b9b2-9a77-4133-99a3-b60f05a12ad1
              \n\n* hmis-globalapi/rest/notifications?status=DELIVERED&recipienttype=clientid&recipientid=cf98b9b2-9a77-4133-99a3-b60f05a12ad1 - Returns all notifications delivered to client Id cf98b9b2-9a77-4133-99a3-b60f05a12ad1
              \n\n* hmis-globalapi/rest/notifications?fromdate=1516546276760&recipienttype=clientid&recipientid=cf98b9b2-9a77-4133-99a3-b60f05a12ad1 - Returns all notifications associated with the client Id from Sun Jan 21 2018 14:51:16 "
    queryParameters:
      fromdate:
        description: |
                "From date" in millisecods - This will fetch all the notifications starting from this date/time.
        type: number
        required: false
      todate:
        description: |
                      "To date" in millisecods  - This will fetch all the notifications until this date / time.
        type: number
        required: false
      recipienttype:
        description: Recipient Type - Currently supported recipient Type is only "ClientID"
        type: string
        required: false
      recipientid:
        description: |
              Recipient Id -  The client identifier (UUID) example: "cf98b9b2-9a77-4133-99a3-b60f05a12ad1"
        type: string
        required: false
      status:
        description: status - Possible statuses that a notification can have CREATED , DELIVERED , FAILED
        type: string
        required: false
      startIndex:
        description: The start Index from where the search results should be returned. Default - 0
        type: number
        required: false
      maxItems:
        description: the number or Items that should be included in the results . Default - 200
        type: number
        required: false
    responses:
      200:
        body:
          application/json:
            example:
              {
                 "notifications":{
                    "pagination":{
                       "from":0,
                       "total":13,
                       "maximum":2,
                       "sort":{

                       }
                    },
                    "notifications":[
                       {
                          "data":{
                             "subject":"Test subject",
                             "status":"CREATED",
                             "recipients":{
                                "toRecipients":[
                                   "surya.yadavalli@gmail.com"
                                ],
                                "bccRecipients":[
                                   "surya.yadavalli@gmail.com"
                                ],
                                "ccRecipients":[
                                   "surya.yadavalli@gmail.com"
                                ]
                             },
                             "body":"Test message",
                             "parameters":{
                                "parameter":[

                                ]
                             }
                          },
                          "method":"EMAIL",
                          "additionalInfo":{
                             "recipientType":"Client",
                             "recipientId":"6997cbb0-4485-4ac8-9a40-f8099726c9e3",
                             "messageType":"message type"
                          },
                          "createdTimeStamp":"01-21-2018 09:54",
                          "lastStatusTimeStamp":"01-21-2018 09:54"
                       },
                       {
                          "data":{
                             "subject":"Test subject",
                             "status":"FAILED",
                             "statusMessage":"Invalid recipient email address",
                             "recipients":{
                                "toRecipients":[
                                   "surya.yadavalli@gmail.com"
                                ],
                                "bccRecipients":[
                                   "surya.yadavalli@gmail.com","support@hslynk.com"
                                ],
                                "ccRecipients":[
                                   "surya.yadavalli@gmail.com"
                                ]
                             },
                             "body":"Test message",
                             "parameters":{
                                "parameter":[

                                ]
                             }
                          },
                          "method":"EMAIL",
                          "additionalInfo":{
                             "recipientType":"ClientId",
                             "recipientId":"6997cbb0-4485-4ac8-9a40-f8099726c9e3",
                             "messageType":"Cancellation Notice"
                          },
                          "createdTimeStamp":"01-21-2018 21:02",
                          "lastStatusTimeStamp":"01-21-2018 21:02"
                       }
                    ]
                 }
              }
/clients/{clientId}/consents:
  post:
    description: Create client consents
    body:
      application/json:
        example: |
          {
             "consent":{
                "clientId":"dcdf2326-0d96-43eb-8368-501b29145c53",
                "startTime":1519914315641,
                "endTime":1543602600000,
                "consentGroupId":"group1",
                "globalProjects":[
                   {
                      "id":"4b84cb25-d27e-458e-ad5d-d817f30390d2"
                   }
                ]
             }
          }
    responses:
      200:
          body:
            application/json:
              example: |
                    {
                     "consent":{
                        "clientId":"dcdf2326-0d96-43eb-8368-501b29145c53",
                        "startTime":1519914315641,
                        "endTime":1543602600000,
                          "consentGroupId":"group1",
                        "globalProjects":[
                           {
                              "id":"4b84cb25-d27e-458e-ad5d-d817f30390d2",
                              "projects":{
                                 "projects":[

                                 ]
                              }
                           }
                        ],
                        "consentId":"db51219d-f439-4250-bdf2-7a1a07816832"
                     }
                    }
  get:
    description: Get consents of selected client
    responses:
     200:
      body:
        application/json:
          example: |
            {
               "consents":{
                  "pagination":{
                     "from":0,
                     "returned":1,
                     "total":1,
                     "maximum":30,
                     "sort":{

                     }
                  },
                  "consents":[
                     {
                        "clientId":"dcdf2326-0d96-43eb-8368-501b29145c53",
                        "status":"APPROVED",
                        "startTime":1519914315641,
                        "endTime":1543602600000,
                          "consentGroupId":"group1",
                        "globalProjects":[
                           {
                              "id":"4b84cb25-d27e-458e-ad5d-d817f30390d2",
                              "projectName":"Project Name",
                              "projectCommonName":"Project common name",
                              "description":" description",
                              "projects":{
                                 "projects":[

                                 ]
                              }
                           },
                           {
                              "id":"6c0f6f77-ba6c-4365-9ce5-3fe65ccdbe86",
                              "projectName":"Project Name",
                              "projectCommonName":"Project common name",
                              "description":" description",
                              "projects":{
                                 "projects":[

                                 ]
                              }
                           }
                        ],
                        "consentId":"db51219d-f439-4250-bdf2-7a1a07816832"
                     }
                  ]
               }
            }
/clients/{clientId}/consents/{consentId}:
  put:
    description: Update a client's consent
    body:
      application/json:
        example: |
          {
           "consent":{
              "startTime":1519914315641,
              "endTime":1543602600000,
                "consentGroupId":"group1",
           }
    responses:
     200:
       body:
         application/json:
           example: |
  get:
    description: Retrive a client's consent
    responses:
     200:
      body:
        application/json:
          example: |
            {
             "consent":{
                "clientId":"dcdf2326-0d96-43eb-8368-501b29145c53",
                "startTime":1519914315641,
                "endTime":1543602600000,
                  "consentGroupId":"group1",
                "globalProjects":[
                   {
                      "id":"4b84cb25-d27e-458e-ad5d-d817f30390d2",
                      "projects":{
                         "projects":[

                         ]
                      }
                   }
                ],
                "consentId":"db51219d-f439-4250-bdf2-7a1a07816832"
             }
            }
  delete:
    description:  Delete a client's consent
    responses:
      200:
        body:
          application/json:
            example: |
/clients/{clientId}/consents/{consentId}/documents:
  post:
    description:  |
      Uploads the consent document (Verbal / signed document) for the client for a specific consent. The content type should be multipart/form-data ( Content-Type: multipart/form-data).
    body:
      multipart/form-data:
        example: |
                Content-Type: multipart/form-data; boundary=WebKitFormBoundarytujNY4RwDez6d3Hk

                --WebKitFormBoundarytujNY4RwDez6d3Hk--
                Content-Disposition: form-data; name="image"; filename="image.jpg"
                Content-Type: application/octet-stream

                ... content of image.jpg ...

                --WebKitFormBoundarytujNY4RwDez6d3Hk--
    responses:
      404:
        body:
          application/json:
            example: |
              {
                  "errors": [
                    {
                      "code": "CLIENT_CONSENT_NOT_FOUND",
                      "message": "Client consent not found : e9a4a447-833f-4c29-a3b6-f966a0a753aa"
                    }
                  ]
              }
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                 "Documents":{
                    "documents":[
                       {
                          "mimeType":"application/pdf",
                          "size":169147,
                          "fileName":"Agenda_Zachary P Test_10Apr2018_1523459800803.pdf",
                          "documentId":"e3dc78a6-b898-42bb-bf7b-02a1236dc5ab"
                       },
                       {
                          "mimeType":"application/pdf",
                          "size":169147,
                          "fileName":"Agenda_Zachary P Test_10Apr2018_1523459739642.pdf",
                          "documentId":"86c7d8e3-f21e-438a-8a03-bdf12bb33abd"
                       }
                    ]
                 }
              }
      404:
        body:
          application/json:
            example: |
              {
                  "errors": [
                    {
                      "code": "CLIENT_CONSENT_NOT_FOUND",
                      "message": "Client consent not found : e9a4a447-833f-4c29-a3b6-f966a0a753aa"
                    }
                  ]
              }
/clients/{clientId}/consents/{consentId}/documents/{documentId}:
  get:
    description: Download consent document
  delete:
    description: delete consent document
    responses:
      200:
        body:
          application/json:
            example: |
      404:
        body:
          application/json:
            example: |
              {
                  "errors": [
                    {
                      "code": "CLIENT_CONSENT_NOT_FOUND",
                      "message": "Client consent not found : e9a4a447-833f-4c29-a3b6-f966a0a753aa"
                    }
                  ]
              }
/clients/{clientId}/consents/{consentId}/projects:
  put:
    description: Replace existing global projects associated with a specific consent with a new set of global projects.
    body:
      application/json:
        example: |
          {
           "globalProjects":{
              "globalProjects":[
                 {
                    "id":"6c0f6f77-ba6c-4365-9ce5-3fe65ccdbe86"
                 },
                 {
                   "id":"8d0f6f77-ba6c-4365-9ce5-3fe65ccdbe97"
                 }
              ]
           }
          }
    responses:
      200:
        body:
          application/json:
            example: |
/clients/{clientId}/consents/{consentId}/projects/{globalProjectId}:
 delete:
   description: Remove global project from a client consent
   responses:
     200:
       body:
         application/json:
           example: |
/search/consents:
  description: |
      Search consents based on given consent group id. In the feature this API will support additonal filters as well.
  get:
    queryParameters:
      consentGroupId:
        description: |
            consentGroupId filter to be applied to the consents.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "consents":{
                  "pagination":{
                   "from":0,
                   "returned":12,
                   "total":12,
                   "maximum":30,
                   "sort":{

                   }
                  },
                  "consents":[
                   {
                      "clientId":"1466033e-6b0b-48c3-a0dc-2a3dec2f5be8",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"5b418fc5-5d9f-4679-aec8-d58040bdedb3"
                   },
                   {
                      "clientId":"d17cbc77-8a08-4b99-9149-21ad14affc76",
                      "status":"APPROVED",
                      "startTime":1519914315641,
                      "endTime":1543602600000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"55816aa2-df75-442c-93ac-6ad3e757e093"
                   },
                   {
                      "clientId":"809cebcc-4ebe-4d20-8883-00f51ef2fcdd",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"290d588c-c515-45a9-bd98-96d548192291"
                   },
                   {
                      "clientId":"b52805f0-5150-47f5-88e4-920983bcf40b",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"816d1f8a-8e85-4f18-bf22-6e543104934e"
                   },
                   {
                      "clientId":"6e45ef10-45d5-4f55-b594-fa50aee0eb86",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"c504fd22-7dc4-4295-bfc7-81c9094e4098"
                   },
                   {
                      "clientId":"e24c4e80-11fd-462d-9aff-2fc7bc50d34a",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"2fcdccad-5375-42a5-88d3-af6704aa6791"
                   },
                   {
                      "clientId":"0b7579c6-4582-437a-b5d0-4fc21d183a3b",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"dfb26458-4d40-44d3-b3df-a3b351eaa026"
                   },
                   {
                      "clientId":"e10d5a05-cd04-41ac-b7d5-b3b122790a61",
                      "status":"APPROVED",
                      "startTime":1491090040001,
                      "endTime":1522626040001,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"b7dec82a-74e3-4c8a-be22-5a3c48b4fa57"
                   },
                   {
                      "clientId":"7c795194-61e2-4962-97d0-602ecc606131",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"ad3b7268-692d-40cf-92ee-79cd4dbe9866"
                   },
                   {
                      "clientId":"9c72a051-b1ac-473c-bb32-ffd3eedbf1ec",
                      "status":"APPROVED",
                      "startTime":1519934115641,
                      "endTime":1543622400000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"de237529-670f-412f-bdb8-3519e74e7560"
                   },
                   {
                      "clientId":"3b270dd0-b5cd-4b0c-b848-d4b1401bed60",
                      "status":"APPROVED",
                      "startTime":1519914315641,
                      "endTime":1543602600000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"d349394a-9a74-4681-8885-03b0c41cea4f"
                   },
                   {
                      "clientId":"2b57db72-dd2b-4878-bf7f-5d375f69d6bc",
                      "status":"APPROVED",
                      "startTime":1519914315641,
                      "endTime":1543602600000,
                      "consentGroupId":"test123",
                      "globalProjects":[

                      ],
                      "consentId":"aa8429ca-b6e2-49bb-b57c-d03bacf22394"
                   }
                  ]
                  }
                  }
